services:
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./src/laravel:/var/www/html"
    depends_on:
      - db
      - php

  db:
      image: bitnami/postgresql:16.3.0
      platform: linux/amd64
      shm_size: 128mb
      ports:
          - "5432:5432"
      restart: always
      volumes:
          - db-data:/bitnami/postgresql
      environment:
          - POSTGRES_DATABASE=fpr
          - POSTGRES_USERNAME=fpr
          - POSTGRES_PASSWORD=secret
      networks:
          - docker-network

  pgadmin:
      image: dpage/pgadmin4
      environment:
          PGADMIN_DEFAULT_EMAIL: admin@admin.com
          PGADMIN_DEFAULT_PASSWORD: secret
      volumes:
          - db-data:/bitnami/postgresql
      ports:
          - "8080:80"
      depends_on:
          - db
      networks:
          - docker-network


  php:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
        - "./src/laravel:/var/www/html"

  composer:
    build:
      context: .
      dockerfile: composer.dockerfile
    volumes:
        - "./src/laravel:/var/www/html"
    working_dir: "/var/www/html"

  npm:
    image: node:current-alpine
    volumes:
        - "./src/laravel:/var/www/html"
    entrypoint: ["npm"]
    working_dir: "/var/www/html"

  artisan:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - "./src/laravel:/var/www/html"
    working_dir: "/var/www/html"
    depends_on:
        - db
        - php
    entrypoint: ["php", "/var/www/html/artisan"]
    networks:
      - docker-network


volumes:
    db-data:

networks:
    docker-network:
        driver: bridge
