services:
  nginx:
    container_name: app_container
    build:
      context: .
      dockerfile: nginx.dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./src/laravel:/var/www/html"
    depends_on:
      - db
      - php
    networks:
      - docker-network
      - docker-testing-network

  db:
      image: bitnami/postgresql:16.3.0
      platform: linux/amd64
      shm_size: 256mb
      ports:
          - "${POSTGRES_OUTER_PORT}:${POSTGRES_INNER_PORT}"
      restart: always
      volumes:
          - db-data:/bitnami/postgresql
      environment:
          - POSTGRES_DATABASE=${POSTGRES_DATABASE}
          - POSTGRES_USERNAME=${POSTGRES_USERNAME}
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      networks:
          - docker-network

  db_test:
      image: bitnami/postgresql:16.3.0
      platform: linux/amd64
      shm_size: 64mb
      ports:
          - "${POSTGRES_TEST_OUTER_PORT}:${POSTGRES_TEST_INNER_PORT}"
      restart: always
      volumes:
          - db-data2:/bitnami/postgresql
      environment:
          - POSTGRES_DATABASE=${DB_TEST_DATABASE}
          - POSTGRES_USERNAME=${DB_TEST_USERNAME}
          - POSTGRES_PASSWORD=${DB_TEST_PASSWORD}
      networks:
          - docker-testing-network

  php:
    user: "${USERID}:${GROUPID}"
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - "./src/laravel:/var/www/html"
      - "/var/www/html/node_modules"
    networks:
      - docker-network
      - docker-testing-network
    environment:
      XDEBUG_MODE: coverage

  composer:
    user: "${USERID}:${GROUPID}"
    build:
      context: .
      dockerfile: composer.dockerfile
    volumes:
        - "./src/laravel:/var/www/html"
    working_dir: "/var/www/html"
    networks:
        - docker-network
        - docker-testing-network

  npm:
    image: node:23-alpine3.20
    volumes:
        - "./src/laravel:/var/www/html"
    entrypoint: ["npm"]
    working_dir: "/var/www/html"
    depends_on:
      - php
      - nginx
    networks:
        - docker-network
        - docker-testing-network

  chrome:
    image: selenium/standalone-chromium:latest
    shm_size: 1g
    container_name: chrome_container
    ports:
      - "4444:4444"
      - "5900:5900"
      - "7900:7900"
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - php
      - nginx
    networks:
      - docker-testing-network


  elasticsearch:
    image: elasticsearch:8.16.4
    container_name: elasticsearch
    depends_on:
      - nginx
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
    deploy:
      resources:
        limits:
          memory: 2g
    volumes:
      - "./es-init:/usr/share/elasticsearch/es-init"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 60s
      timeout: 10s
      retries: 5
    networks:
      - docker-network


volumes:
    db-data:
    db-data2:

networks:
    docker-network:
    docker-testing-network:
        driver: bridge
